### ISSUE TITLE
iotile-ship - autobuild_shiparchive unable to create .ship archives if a custom Step is necessary

### ISSUE THREAD

**Issue by x24ling** [iotile/coretools#504]
For the instance of building scripts for the pod_1m, which relies on a custom ActionStep, CalibratePOD1MStep, it fails 
```
 File "c:\users\chris\iotile\coretools\iotilebuild\iotile\build\config\scons-local-3.0.1\SCons\Action.py", line 1197, in execute
    result = self.execfunction(target=target, source=rsources, env=env)
  File "c:\users\chris\iotile\coretools\iotileship\iotile\ship\autobuild\ship_file.py", line 107, in create_shipfile
    resman.add_recipe_folder(source_dir, whitelist=[os.path.basename(str(source[0]))])
  File "c:\users\chris\iotile\coretools\iotileship\iotile\ship\recipe_manager.py", line 79, in add_recipe_folder
    recipe = RecipeObject.FromFile(os.path.join(recipe_folder, yaml_file), self._recipe_actions, self._recipe_resources)
  File "c:\users\chris\iotile\coretools\iotileship\iotile\ship\recipe.py", line 215, in FromFile
    action=action_name, step=i + 1, path=path)
UnknownRecipeActionType: UnknownRecipeActionType: Unknown step specified in recipe
Additional Information:
action: CalibratePOD1MStep
path: build\none\calibrate_pod1m\calibrate_pod1m.yaml
step: 3
```

The reason for this is that autobuild_shiparchive calls the following functions
```
resman = RecipeManager()
resman.add_recipe_folder(source_dir, whitelist=[os.path.basename(str(source[0]))])
recipe = resman.get_recipe(recipe_name)
```

Which relies on RecipeManager reading from entry_points to determine the list of valid RecipeActions, but this is a problem if this package has not been installed yet, which is the case when we're building the package.

**Comment by x24ling** [comment]
Just realized I may need to use product_resolver in the template, give me a second to verify this.

**Comment by x24ling** [comment]
I tried doing something like `{ "build_step, calibrate_pod1m_step.py:CalibratePOD1MStep" | find_product }` but i just realized that's only good for files, not step definitions.

**Comment by x24ling** [comment]
Some solutions I thought of, I'm not really sure what the best option is:

1. Inside autobuild_shiparchive, manually add an entrypoint for each build_step product to pkg_resources before ResourceManager() is called. Seems really hacky, will need to verify if this will indeed change it globally, but it will a pretty minimal fix.

2. Pass the products that are build_steps into ResourceManager(). Inside init() of ResourceManager, add those products into self._recipe_actions. Requires adding new arguments to two functions.

**Comment by x24ling** [comment]
function in question:
https://github.com/iotile/coretools/blob/master/iotileship/iotile/ship/autobuild/ship_file.py

**Comment by timburke** [comment]
So the issue is that `autobuild_shiparchive` needs to access custom ship steps that are defined in the same module that is calling`autobuild_shiparchive`.

The problem is that:
- RecipeManager does not have a way to load custom RecipeAction objects that are not `pip installed`.
- the custom actions need to be loaded in order for the recipe to be archived.

My recommended solution is:
- modify RecipeManager to allow custom loaded RecipeAction objects by adding an `add_recipe_actions` public method
- modify autobuild_shiparchive to load recipe action steps from the current module by looking for them in the ProductResolver using something similar to this:
https://github.com/iotile/coretools/blob/master/iotilecore/iotile/core/hw/hwmanager.py#L765
