### ISSUE TITLE
Option for iotile depends update to only update local.

### ISSUE THREAD

**Issue by ekkizogloy** [iotile/coretools#542]
It would be great if there was a way for `iotile depends update` to just update local dependencies. 

I propose an `iotile depends update_local` that does just that. There already is a command `iotile depends list_local` identifies the local dependancies. `update_local` would just update those dependencies.

**Comment by timburke** [comment]
I'm on board with this idea.

The relevant implementation code is here:
- `list_local`: https://github.com/iotile/coretools/blob/master/iotilebuild/iotile/build/dev/depmanager.py#L37

It's a little involved to figure out which dependencies have been resolved locally since technically the DependencyManager doesn't really know that information.  See the implementation of `list_local` above.  It just tells you which dependencies **could be resolved locally**, not which ones actually were resolved locally.

DependencyManager does save a `dep_settings.json` file into the dependency that says what resolver class it used to find it.  `DependencyResolverChain` uses this information to make sure that once it resolves a dependency it always uses the same resolver to keep it up to date.  See:
- https://github.com/iotile/coretools/blob/master/iotilebuild/iotile/build/dev/resolverchain.py#L141
- https://github.com/iotile/coretools/blob/master/iotilebuild/iotile/build/dev/resolverchain.py#L205

So implementing `update_local` would need:
- `DependencyManager` to inspect `dep_settings.json` for installed dependencies and see which ones have a class name of `ComponentRegistryResolver` indicating they were resolved locally.  Then it can update only those.

A caveat with this approach would be that it would only work after `iotile depends update` has been called at least once to initially populate the dependencies since it's not guaranteed that `ComponentRegistryResolver` is the highest priority dependency resolver.
