### ISSUE TITLE
Identify bled112 + websocket broadcast bottleneck

### ISSUE THREAD

**Issue by timburke** [iotile/coretools#864]
The output of this issue should be a plan that identifies how we can support 2000 received broadcasts per second from 100 devices (so devices broadcasting at 50 ms intervals).  

This can involve changes or streamlined code in `iotile-gateway`, `iotile-transport-bled112`, `iotile-transport-websocket` and/or the creation of a new transport plugin `iotile-transport-tcp` that is more speed optimized.

The current plan of record (which has not been validated as addressing the actual root cause, its just a gut feeling) is that:
- `iotile-transport-bled112` needs to be optimized and potentially refactored into a completely asyncio version to avoid handing data between threads.  
- `iotile-transport-websocket` needs to be deprecated for this use case in favor of a newly created `iotile-transport-tcp` plugin that using a pure tcp based protocol that leveages asyncio's native C support for tcp based sockets, whereas the `websocket` package is entirely implemented in python.

**Comment by DimaWittmann** [comment]
I tried comparing a primitive client/server application using native tcp/ip sockets
and websockets. Client just writes byte chunks of size 31 and server receive it and drop.
The difference is significant, with native sockets it takes around 0.5s to transmit 100 000
chunks against 10-15s with websocket, about 5 times faster.

If we consider profiling gateway with and without web socket code works around 25% of the time.
And bled can handle 25% more packets. I can assume that using tcp sockets instead of websocket 
can improve throughput by 10-15%

Reading packets from the queue of AsyncBuffer takes about 7% of time, rewriting BledAdapter
using asyncio can eliminate for some extend IPC with additional threads.

As it's expected that data duplicates it self, additional filtering can be applied so packets with the same values can be dropped with some timeout, (for example, don't repeat the same packets for 1 second).
A packet aggregation might be applied also, instead of passing a single event back and forth we might try sending a bunch of event that came during last second, for example. It can increase throughput between gateway and client connected via network.

**Comment by DimaWittmann** [comment]
I also tried running the profiler scripts on a Raspberry Pi 3, it is target board for the gateway, isn't it?
I conducted a few experiments, it looks like when I supplied a lot of broadcast data, 500-1000 adv/s the websocket plugin could not keep up with bledadapter (bledadapter has handled around 90 000 packets and ws plugin only around 28 000 for particular example sending 1000 adv/s for 300 seconds)

Another observation is that RPi can handle from 100 to 200 adv/s. When the number of packets reach the limit the number of buffered packets for web socket get increased. 

Experiment with 100 and 150 adv/s for 300 seconds (CPU utilization is below 100%) shows that overall time taken by web socket code is around 25-30%, BLED adapter utilize less than 10%. 

Having that seen I can assume that handling a single packet in web socket code takes 3 times more time that in BLED adapter and so far this is a bottleneck

**Comment by DimaWittmann** [comment]
Please, find below logs:

This log shows that gateway handled around 45 000 packets during 5 minutes, it took `_client_callback`  113 seconds to handle packets against `BLED112CommandProcessor._process_events` 36 seconds
[log_rpi300_150.txt](https://github.com/iotile/coretools/files/3468383/log_rpi300_150.txt) 

This is another example with not full CPU utilization:
[log_rpi300_100.txt](https://github.com/iotile/coretools/files/3468384/log_rpi300_100.txt)

This log shows that when gateway receive too many packets web socket is not able to keep up with bled code `BLED112Adapter._handle_event` is called 93228 times and `_client_callback` -  only 29134.  
[log_rpi300_2000.txt](https://github.com/iotile/coretools/files/3468389/log_rpi300_2000.txt)

Please, feel free to ask any questions you have

**Comment by mattrunchey** [comment]
It's not surprising that the websockets side of the code takes longer, because it's generally doing more work. In the `iotile-gateway` process, it is basically:
- The bled112-adapter, which reads data from the serial device.
- The websocket client, which gets data from the bled112 adapter. It has to (1) read/get the data, and then (2) send it to the websocket server
- The websocket server, which lives on the same process, has to (3) accept the client's data, and (4) serve it to other connected clients.

**Comment by mattrunchey** [comment]
Seems that we've done the work needed here, artifacts checked in with #869 and @timothyfroehlich is working on a more efficient plugin.
