### ISSUE TITLE
Add support for matching proxies to tiles using firmware version

### ISSUE THREAD

**Issue by timburke** [iotile/coretools#876]
Currently, we only match proxies to tiles if the module name matches.  If multiple proxies are installed with the same module name, the "first one" loaded will win always.

However if you install 2 versions of a tile support package, say:

```
iotile-support-con-nrf52832-3
iotile-support-con-nrf52832-4
```

For two different major firmware versions, it should be able to use the `ModuleVersion()` information from the proxy to restrict what tile it matches.  

Most existing proxies won't have a ModuleVersion() classmethod, which should be interpreted to mean that they match all firmware versions for backwards compatibility with the current behavior.

**Notes**

- The key place to modify is [here](https://github.com/iotile/coretools/blob/master/iotilecore/iotile/core/hw/hwmanager.py#L779)
- You should expect `ModuleVersion`, if present in the proxy, to return a list of `SemanticVersionRange` objects which are used to match the firmware version loaded from the tile

**Comment by anwu** [comment]
@timburke Your link pointed me to a slack archive. Did you mean to point somewhere in `proxy.py` in coretools?

**Comment by anwu** [comment]
Closes https://github.com/iotile/lib_controller/issues/199

**Comment by timburke** [comment]
@anwu Thanks, https://github.com/iotile/coretools/blob/master/iotilecore/iotile/core/hw/hwmanager.py#L779

**Comment by anwu** [comment]
> @anwu Thanks, https://github.com/iotile/coretools/blob/master/iotilecore/iotile/core/hw/hwmanager.py#L779

I've been looking through the code and I think [this ](https://code.eng.archsys.io/github.com/iotile/coretools@8cf93381d69dcfc6768885420cfd0d8b7881e771/-/blob/iotilecore/iotile/core/hw/proxy/external_proxy.py#L12)is the correct place to modify.
The location you linked deals with actual tile proxies. Where the location I linked deals with proxy plugins that you get from support packages I think.

**Comment by timburke** [comment]
There are a couple of things going on here that need to be disentangled:

1. How proxy classes are matched to tiles.
2. How the controller proxy finds "proxy plugins" from `lib_controller`.

### Matching Proxies to Tiles

This process is governed by the location in `HardwareManager` that I linked to and needs to be updated to support including `ModuleVersion()` in the match criteria, when specified.

### Assembling the controller proxy

The `NRF52 ` controller proxy is a bit special because proxies are defined at the tile level so `con_nrf52832` has a proxy.  However, there is very little in `con_nrf52832` that is not just a wrapper of `lib_controller`.  For that reason, you would expect that the actual proxy class would be defined in `lib_controller` and `NRF52832Controller` would inherit from it.  However, when the controller proxy was first put together, we did not support class inheritance across support modules because it wasn't possible to `import` the module code unless it was `pip installed` so this would have broken `iotile registry add_component`.  

That underlying problem has since been fixed so there's no longer actually a need for the `proxy_plugin` system since we can use normal class inheritance now.

So, there are two issues to address, the original one about matching tile proxies to tiles using firmware version as well as firmware name and this other issue of removing the need to have `proxy plugins`.  @anwu I'll file a separate internal issue about removing the proxy plugins which aren't needed anymore.

**Comment by anwu** [comment]
@timburke I think I'm not completely understanding exactly how we want to match the proxy to tiles. My assumption right now is that we should be able to look at the [tile's version](https://github.com/iotile/coretools/blob/master/iotilecore/iotile/core/hw/hwmanager.py#L170), and compare it to the proxy's `ModuleVersion` right? However, the proxy in both support packages for con_nrf52832 do not contain that function. So are we looking to have a final `iotile-support-con-nrf52832-3` version that contains a function `ModuleVersion` that, lets say, returns a version 3? And also `iotile-support-con-nrf52832-4` to contain a function `ModuleVersion` that returns version 4?

**Comment by timburke** [comment]
It should be backwards compatible with current proxies.  

Right now we do not use module version at all so current proxies don't implement it, you're right but the implementation would be the same if some did and some didn't.  

Given that, you will have a situation where `iotile-support-con-nrf52832-3` has no `ModuleVersion`.  Similarly, `iotile-support-con-nrf52832-4` does have a module version.  

If you have a firmware with `tile_version` `4.0.0`, which do you use?  Technically both match since one matches `^4.0.0` and the other matches `*`.  There are two potential options:

- Try to figure out which one "matches best" defined as "most specific".  In this case `^4.0.0` is more specific than `*`.
- Don't treat a missing `ModuleVersion` as a wildcard.  Instead treat it as matching the same major version of `tile_version` indicated by the `-X` at the end of the python distribution name (`iotile-support-name-X` containing the proxy.

@mattrunchey Can you help provide some architectural guidance here on how to update the `HardwareManger` proxy system to take `tile_version` into account instead of just `tile_name`.

It's the same system we use in matching `IOTileApp` to `app_tag` and `app_version`

**Comment by anwu** [comment]
Okay that is pretty much how I've began implementing it thus far (with `iotile-support-con-nrf52832-4` with `ModuleVersion()` and without touching the old `iotile-support-con-nrf52832-3`). Think I've got it from here...

**Comment by mattrunchey** [comment]
Looks like we already pull in the `tile_version` in `get`. Talked with @anwu and he seems to have found a good track by passing the version through to `get_proxy` and then matching it when the short_name has multiple matches. I hesitate to try and get too clever with this matching section -- we have few enough modules that optimizing our search is not going to be worth much, and what he already has implemented seems to work.

I think that it's important to unlock the capability for tile_version for other proxy modules though, looking through this I realized we have the exact same problem with some of the node products we put out. We have 0.6 and 0.9 in the field, but you have to install from older packages to get 0.6 proxies and uninstall your 0.9 proxies. If instead we registered multiple proxies with the same tile name, but used SemanticVersion as an optional comparator, we could modify the way the installed packages work and keep them all together. 

So ultimately, looking at it, the changes will look something like:

- Load modules by version now `self._name_map[short_name][version]` . by default, `version` should be `None`. This will also let us maintain the same duplication drop out as we had before.
- Modify the function signature of `get_proxy` to something like `def get_proxy(self, short_name, version=None)` now takes a SemanticVersion argument and attempts to match versions closely (specifically, as @timburke mentioned in the earlier comment)

*Note* I'm not sure if `SemanticVersion` supports comparing against `None`, so instead of defaulting to `None` you might need to use some form of default SemVer in `_setup_proxies` like
```
try:
  version = SemanticVersion(obj.ModuleVersion())
except TheRightException:
  version = SemanticVersion("0.0.0")
```

**Comment by timburke** [comment]
You'll want both SemanticVersion and `SemanticVersionRange`.  

`ModuleVersion()` should return `SemanticVersionRange` objects not `SemanticVersion` objects.  There's an example in HardwareManager for how we do IOTileApp matching:
https://code.eng.archsys.io/github.com/iotile/coretools/-/blob/iotilecore/iotile/core/hw/hwmanager.py#L239

**Comment by anwu** [comment]
Yup, that was my next step. I just wanted to push something that had functionality. Thanks for the reference link, I'll check it out now...
