### ISSUE TITLE
Something is causing us to see double BroadcastReports

### ISSUE THREAD

**Issue by mattrunchey** [iotile/coretools#877]
We have a few PODs set up to broadcast at an interval of 100ms. This interval was confirmed by a 3rd party app (NRF Connect). As a result, we expect to see a maximum of 10 unique broadcast packets per second when we are looking at them here (with `watch_broadcasts` or `iter_broadcast_reports`). 

However, we are seeing around 15 broadcasts per second. Here is a snippet of what the contents of the IOTileReadings look like:
```
{'device_timestamp': 4970, 'stream': 4136, 'timestamp': '1970-01-04T19:26:40.021661', 'value': 8, 'streamer_local_id': 0}
{'device_timestamp': 4970, 'stream': 4136, 'timestamp': '1970-01-04T19:26:40.021661', 'value': 8, 'streamer_local_id': 0}
{'device_timestamp': 4970, 'stream': 4136, 'timestamp': '1970-01-04T19:26:40.133200', 'value': 8, 'streamer_local_id': 0}
{'device_timestamp': 4970, 'stream': 4136, 'timestamp': '1970-01-04T19:26:40.133200', 'value': 8, 'streamer_local_id': 0}
{'device_timestamp': 4970, 'stream': 4136, 'timestamp': '1970-01-04T19:26:40.242691', 'value': 8, 'streamer_local_id': 0}
{'device_timestamp': 4970, 'stream': 4136, 'timestamp': '1970-01-04T19:26:40.242691', 'value': 8, 'streamer_local_id': 0}
{'device_timestamp': 4970, 'stream': 4136, 'timestamp': '1970-01-04T19:26:40.265342', 'value': 8, 'streamer_local_id': 0}
{'device_timestamp': 4970, 'stream': 4136, 'timestamp': '1970-01-04T19:26:40.265342', 'value': 8, 'streamer_local_id': 0}
{'device_timestamp': 4970, 'stream': 4136, 'timestamp': '1970-01-04T19:26:40.377426', 'value': 8, 'streamer_local_id': 0}
{'device_timestamp': 4970, 'stream': 4136, 'timestamp': '1970-01-04T19:26:40.377426', 'value': 8, 'streamer_local_id': 0}
{'device_timestamp': 4970, 'stream': 4136, 'timestamp': '1970-01-04T19:26:40.486444', 'value': 8, 'streamer_local_id': 0}
{'device_timestamp': 4970, 'stream': 4136, 'timestamp': '1970-01-04T19:26:40.486444', 'value': 8, 'streamer_local_id': 0}
```

The key thing to point out here is that each IOTileReading seems to be duplicated and has the exact same `timestamp` field. In reality, we're seeing around 7.5 broadcasts per second -- but are parsing 15 due to duplication.

It's not clear where this duplication is happening. The behavior is consistent regardless of the `active-scan` setting, and `BroadcastReport` is only used in two places in the BLED112 transport plugin code (in https://github.com/iotile/coretools/blob/master/transport_plugins/bled112/iotile_transport_bled112/bled112.py#L637 and https://github.com/iotile/coretools/blob/master/transport_plugins/bled112/iotile_transport_bled112/bled112.py#L718 ). 

If you want to do any verification of this, you can use something similar to the following script to print out the readings of any specific device:

```python
from iotile.core.hw import HardwareManager
from datetime import datetime
import asyncio 
import time

device_map = {}

def _handle_broadcast(report):
    device = report.origin
    if device not in device_map:
        device_map[device] = {'num_broadcasts': 1}
    else:
        device_map[device]['num_broadcasts'] += 1
    
    if device == 2964:
        print(report.decode()[0][0].asdict())

with HardwareManager(port='bled112') as hw:
    hw.enable_broadcasting()
    starttime = datetime.now()
    while 1:
        try:
            for report in hw.iter_broadcast_reports(blocking=False):
                _handle_broadcast(report)
            time.sleep(0.5)
        except (asyncio.CancelledError, KeyboardInterrupt):
            print("Task Cancelled by Ctrl+C")
            break
        
        checktime = datetime.now()
        print('0xB94 : ' + str(device_map[2964]['num_broadcasts']/(checktime-starttime).seconds))
        #for device in device_map:
        #    print(str(device) + ": " + str(device_map[device]['num_broadcasts']/(checktime-starttime).seconds)) 

```

**Comment by mattrunchey** [comment]
I  believe i found the source of doubling broadcast messages. https://github.com/iotile/coretools/blob/8cf93381d69dcfc6768885420cfd0d8b7881e771/iotilecore/iotile/core/hw/transport/adapter/mixin_notifications.py#L184 . It seems that both the wildcard_handlers and event_handlers both have a _on_notification callback registered. Not yet sure why there are two handlers, but fixing that should resolve this.

**Comment by timburke** [comment]
So, here's the problem.  It's a combination of factors.  First, the cause:

1. The new notification system is setup so that all events should be associated with a device and hence have a non-None connection string, even broadcast reports.  However, legacy DeviceAdapter classes that were around before the `asyncio` refactor were not rewritten and instead a `ModernAsynchronousWrapper` class was written that provided the modern api on top of the old class.
2. The old device adapter class did not have a concept of "connection string" that it could associate with broadcast reports.  The `callback` used for broadcast reports was the same one used for normal streamer reports so it had a "connection id" that was non-null for streamer reports and null for broadcast reports.  
3. So you can get a `broadcast` event with a none connection string if it came from a legacy device adapter.
4. `None` as the connection string was how we chose to record a wildcard monitor in `BasicNotificationMixin` when building modern device adapters.
5. It was assumed that registering the monitor with a connection string of `None` would make it never match directly any event since they always have a non-None connection string.
6. However, that's not the case so the same monitor is found twice (once because it's a wildcard) and once again because its registered connection string `None`, exactly matches the connection string in question (`None`) for broadcast reports.

See:
- https://github.com/iotile/coretools/blob/master/iotilecore/iotile/core/hw/transport/adapter/async_wrapper.py#L242
- https://github.com/iotile/coretools/blob/master/iotilecore/iotile/core/hw/transport/adapter/mixin_notifications.py#L178

The fix is needed [here](https://github.com/iotile/coretools/blob/master/iotilecore/iotile/core/hw/transport/adapter/mixin_notifications.py#L178).  If the conn_string is None, we shouldn't look for exact matches in the monitors since we would find those same monitors via the wildcard logic to avoid duplicates.

Longer term this is already fixed for non-legacy device adapters that include a proper conn_string with their broadcast reports.
