### ISSUE TITLE
RPC Decorator possibly incompatible with type hints

### ISSUE THREAD

**Issue by mattrunchey** [iotile/coretools#912]
A simple example:

```python
    @rpc(8, 0x9904, "", "d")
    def get_median(self) -> float:
        """Return median of the readings"""
        if len(self.readings) == 0:
            return [0.]
```

This prompts a `mypy` warning :
<img width="722" alt="Screen Shot 2019-12-03 at 3 52 28 PM" src="https://user-images.githubusercontent.com/3580926/70099878-fd065980-15e4-11ea-8b30-aeac36a4d9bf.png">

A few possible ways to solve this:

1. We figure out how to enable mypy type hints to "work" on RPC decorated functions (hard)
2. We disable mypy warnings that occur within the function like we do linting (ugly)
3. We don't bother hinting RPCs because the function isn't typically designed to be explicitly 
called, and the type is already explicit in the decorator anyways (easy). 

I don't think it will be easy to accomplish (1) but also haven't exhaustively searched for people who have similar issues. 

I envision (3) being the best thing for us to do, but wanted to open a discussion and document the decision in an issue (and perhaps in the RTD/style guide).

**Comment by timburke** [comment]
I'm not sure that the RPC decorator is involved in this error.  I read mypy as saying:

- You promised me you would return a `float` and you instead returned a `List[float]`.

The type signature of `get_median` should just be `List[float]` because that's what it's returning.  The RPC decorator doesn't change the return value in anyway.  It always expects the methods its decorating to return an iterable of values and it uses its format string to marshal them into a binary string for transport.  

What am I missing here?

**Comment by mattrunchey** [comment]
You're not missing anything, I was incorrectly assuming that there'd be an error in the caller if you had `List[float]` because the consumer variable stores the result as a `float`. What I failed to do is complete the analysis with "but nobody is actually calling `get_median` directly because the result is being processed through the RPC mechanism (like `var = self.rpc_v2(0x9904)`).
