### ISSUE TITLE
better error type for unexpected disconnects

### ISSUE THREAD

**Issue by JKHeadley** [iotile/coretools#918]
https://code.eng.archsys.io/github.com/iotile/coretools@87f7913de0fdcb1ccb6277bd7f03eda26cb81db5/-/blob/iotilecore/iotile/core/hw/transport/adapterstream.py#L266

Currently raises a `HardwareError`

Maybe consider a new `UnexpectedDisconnectError` for better specificity.

See: https://github.com/iotile/iotile-factory-companion/issues/35

**Comment by mattrunchey** [comment]
Yea, looking at it, kind of funny it's basically `raise HardwareError from exc` and `exc` is already `HardwareError`, so this is a great place to be more specific (as it's in the `_try_reconnect` routine.

If you want to add this as a new exception class, I think we typically add them [here](https://code.eng.archsys.io/github.com/iotile/coretools/-/blob/iotilecore/iotile/core/exceptions.py#L84) and then you'd just import it and drop in on line 266 in `adapterstream.py`

**Comment by timburke** [comment]
@JKHeadley We should discuss how you plan to use this inside your app because it's not going to work as reliably as you might expect.  Disconnects can happen at any time and you may or may not be in the middle of an operation when one does so counting on getting an exact exception when you disconnect could end up being quite brittle in practice.

The current bled112 device adapter stack in particular has some trouble reliably telling the difference between a disconnection and a timeout from a slow rpc.

If you're trying to figure out why an RPC failed, remember that the `proxy` always distinguishes between an application level failure and a hardware failure.  Generic Hardware Failures are pretty much always going to be due to a disconnection.  The other exceptions you can get from an RPC protocol level are all here:
https://github.com/iotile/coretools/blob/master/iotilecore/iotile/core/hw/exceptions.py#L94

So, if you can describe a bit more how you plan on using this, there may be a better way that doesn't need a custom error.

To be clear, I think we should have a nice disconnected error but it's really hard to actually make it reliably get thrown so let's brainstorm how else we could solve this problem.

**Comment by JKHeadley** [comment]
@timburke Thanks for the insight. Currently the app registers a disconnect handler to detect when unexpected disconnects occur and the app notifies the user to re-connect:
https://github.com/iotile/iotile-factory-companion/blob/master/electron/coretools-api/grpc/factory_companion_server.py#L132

The refactored version (https://github.com/iotile/iotile-factory-companion/pull/36) is simplified and aims to follow the suggested flow presented by coretools where, upon unexpected disconnect, the app attempts to reconnect on the next rpc call. I've tested this flow in practice and it seems like a better user experience to me.

For example, a user connects to an AP, then starts sending rpcs. At some point the app looses connection with the AP, but doesn't alert the user until `_try_reconnect` fails and reports an error. At this point I would like to present an error message to the user similar to: "An unexpected disconnect occurred. Make sure you are within range of the device and try again."

I've manually tested this with my test AP by powering it off after connecting, attempting to send rpcs, powering it back on, then continuing to attempt commands until it successfully re-connects.

I could detect the `HardwareError` thrown in `_try_reconnect` by matching its error message, but ideally we could replace it with a disconnect error so that it could be detected more clearly/cleanly.

**Comment by JKHeadley** [comment]
For context, this is the error I'm receiving on the JS side:

```
{ type: 'HardwareError',
     reason:
      'Device disconnected unexpectedly and we could not reconnect',
     params:
      '{"reconnect_error": {"reason": "Operation connect on conn 0 failed because Timeout opening connection", "type": "DeviceAdapterError", "params": {"reason": "Timeout opening connection", "operation": "connect", "conn_id": 0}}}' }
```

So I guess technically I could detect if the `reconnect_error` param is present.

**Comment by JKHeadley** [comment]
After discussing this with @timburke, it looks like it would be more hassle than its worth to change this error. In addition, any `HardwareError` should by default imply a disconnect.
