### ISSUE TITLE
Python3.7: iotile-transport-websocket requires websockets ~=7.0, incompatible with latest release

### ISSUE THREAD

**Issue by timothyfroehlich** [iotile/coretools#922]
In a Python3.7 virtualenv, while running this pip install command:
```pip installpytest
pexpect
pyserial
columnar
pylint
iotile-core
iotile-support-con-nrf52832-3
iotile-support-con-nrf52832-4
iotile-support-lib-controller-3
iotile-support-lib-controller-4
iotile-transport-bled112
pycryptodome
arch-node-tasks/```

This error is reported immediately before installing the packages:
`ERROR: iotile-transport-websocket 3.1.0 has requirement websockets~=7.0, but you'll have websockets 8.1 which is incompatible.`

I don't know which package is causing that version to be pulled in and I don't know if it causes any problems. Not sure what to do about it.

**Comment by mattrunchey** [comment]
How is it that there isn't an error path showing which package is pulling that dependency? It seems like you're missing a lot of what pip should output when there's an error. Can you try to get a more verbose log?

This should have nothing to do with python version, unless some chained dependency changed version and required a specific WS.

**Comment by mattrunchey** [comment]
This should probably not be filed in coretools, as it deals with private arch repos, and also seems unrelated to coretools. This seems like something we should be able to resolve in slack.

If you do identify a problem with coretools specific items, definitely reopen it.

**Comment by mattrunchey** [comment]
OK, so there is something going on that is outside of this repo impacting here, but there still may be a coretools change to implement.

We run a package that doesn't specify which websockets version we need, so the default that often gets installed is websockets 8.

I cannot find an issue stating that we are required to use 7.0 -- it appears that it was chosen so that we didn't auto upgrade to 8.0 when it released, but it was also possible that it does break (perhaps we need to test this).

@timburke Are you aware of a functional limitation that made us use `~7` for websockets? If not, we maybe should explore upgrading to `websockets~=8` 

@timothyfroehlich and for anyone else who's hitting this issue, it's likely because you are attempting to install `hbmqtt` first, which doesn't lock down the version and pypi collects 8 first (https://github.com/beerfactory/hbmqtt/blob/master/setup.py#L21) . However, no Arch packages require 8 explicily (at this time of writing), so if you simply run `pip install websockets~=7` before running other installs, you should be able to avoid this issue.

**Comment by timothyfroehlich** [comment]
"so if you simply run pip install websockets~=7 before running other installs, you should be able to avoid this issue."

That'll simply cause Pip to not display a warning, the actual issue is whether or not coretools is compatible with websockets 8.

This is also a python version issue, since websockets 7 required Python >=3.4 but websockets 8 requires Python >= 3.6

**Comment by mattrunchey** [comment]
Ok, then that's a reason that we can't promote to websockets 8. We need to make a change in our dependent package that pulls in hbmqtt to use 7.0

**Comment by mattrunchey** [comment]
Opened tracking issue in the dependent package to fix it there. Thanks!
